### ISSUE TITLE
not a issue but can we get a 0 xp or a 0 hit drop when we dont hit?

### ISSUE THREAD

**Issue by MainMan11** [geeckon/instant-damage-calculator#16]
it would be a huge help for prayer flicking if we could get a xp drop for when we hit 0s or when the display damage overlay is on if we could get a 0 hit drop it would be a huge help. i use the xp drop to help with my prayer flicking. Please help a brother out lol for melee and range at least. thank you.

**Comment by geeckon** [comment]
The plugin gets info about an attack by tracking xp gains. I would have to rewrite it to do this and not currently planning to do that.
