### ISSUE TITLE
XP drops not shown for splashes

### ISSUE THREAD

**Issue by colesie** [geeckon/instant-damage-calculator#2]
Teleblocks, teleports, high alchemy and other spells which do not deal damage do not display when 'replace XP drops' is toggled on.  It is useful to see the XP drops on entangles/tbs etc to know if they landed or not

![image](https://user-images.githubusercontent.com/84428149/139956743-e411f1eb-5317-432b-a5a5-a0c4b190aca2.png)

**Comment by geeckon** [comment]
@colesie 
Currently I am clearing the text of all combat xp drops and replacing the HP xp drop with the damage done. I do this because the HP xp drop will always be there.
A lot of work is done just to account for split xp drop settings. I could go more into relying on the grouped xp drop setting being turned on which would allow for any xp drop that doesn't contain HP (thus isn't a hit) to be shown normally.

**Comment by colesie** [comment]
> @colesie Currently I am clearing the text of all combat xp drops and replacing the HP xp drop with the damage done. I do this because the HP xp drop will always be there. A lot of work is done just to account for split xp drop settings. I could go more into relying on the grouped xp drop setting being turned on which would allow for any xp drop that doesn't contain HP (thus isn't a hit) to be shown normally.

A good example of what you're trying to accomplish here may be how Exilent client handles true dmg drops. The normal XP drop is displayed but in brackets the true damage is shown. This helps for seeing the splashes as xp drops without having to make a ton of exceptions for every spell in the game? Idk if this is harder or easier than what you have planned, but it works well for Exilent.

It might also help with the bit of lag-time there currently is between the attack and the xp drop.
![image](https://user-images.githubusercontent.com/84428149/139970917-5b3033a5-1723-418b-b770-44df4d9eeb3c.png)

**Comment by geeckon** [comment]
@colesie 
I am using the vanilla xp drop and replacing the xp drop with the hit value. Sadly there just isn't enough space in that widget to add text (to put the hit in brackets). Maybe I can try to figure out how to change the size of it, not sure if that can be done.
