### ISSUE TITLE
Suggestion: add timer-based fade to damage overlay

### ISSUE THREAD

**Issue by mikaels1997** [geeckon/instant-damage-calculator#20]
Currently the latest damage overlay stays visible indefinitely.
It would be cool to have an option to make the overlay automatically disappear after X amount of time.

**Comment by geeckon** [comment]
Should be easy enough to make. I'll get on it when I remember/have the time.

**Comment by geeckon** [comment]
Done in fbaf308b8fa59939b13bfb4f070000cf417d7e46
Added a pull request, should be available in Runelite soon.
