### ISSUE TITLE
Damage dealt wont show correctly in barbarian assault

### ISSUE THREAD

**Issue by kiivikivi** [geeckon/instant-damage-calculator#4]
I know this is pretty minor detail and won't affect many users but this would have some niche uses in barbarian assault speedruns since it would display the hit ~1 tick earlier than it would normally be shown on the npc. Currently it shows "1" everytime when hitting fighters/rangers in the minigame and doesn't actually show the true dmg. I don't know anything about coding or anything like that so I'm just curious if this would be possible to fix. Amazing plugin either way! <3

**Comment by geeckon** [comment]
This is because I calculate the hits based on xp gained and you get no experience in this minigame.
