### ISSUE TITLE
Account for modified XP gains from certain NPCs

### ISSUE THREAD

**Issue by fuzxi** [geeckon/instant-damage-calculator#6]
Some NPCs have an [experience multiplier](https://oldschool.runescape.wiki/w/Combat#PvM_bonus_experience) that increases or decreases combat XP gained when fighting them. Examples include [Tree spirits](https://oldschool.runescape.wiki/w/Tree_spirit) at 2.5% XP and [Cerberus](https://oldschool.runescape.wiki/w/Cerberus) at 115% XP. The plugin currently does not account for these multipliers, making the calculated damage value inaccurate against some NPCs.
Would it be feasible to check what NPC is under attack and divide the gained XP by that NPC's XP multiplier, before calculating damage?

**Comment by geeckon** [comment]
@fuzxi 
There is code that accounts for the xp modifiers. It might not work perfectly because of having an incomplete list of npcs with boosted xp, but it does include Cerberus. 
Is it not working properly?

**Comment by fuzxi** [comment]
After some more testing, it does work properly in most cases. The actual NPCs I had tested it on were Tree spirits and Paterdomus temple monks, both of which have significantly reduced XP gains, and the plugin didn't seem to account for that. Cerberus was just an example of an NPC with increased XP gain, I didn't test it there.

**Comment by geeckon** [comment]
All xp modifiers that are not hardcoded in the plugin can now be customized in the settings after https://github.com/geeckon/instant-damage-calculator/pull/8
