### ISSUE TITLE
Can u add choice for adding additional damage dealt next to current xp drop (on top or under )without replacing it?

### ISSUE THREAD

**Issue by gytosas** [geeckon/instant-damage-calculator#7]

**Comment by geeckon** [comment]
@gytosas 
That was my original intention, but I ran into a problem that the xp drop widget has a set size and it doesn't have enough space for the xp drop and the damage hit. I am sure this can be overcome, but I didn't dive into widgets deep enough to solve this issue and instead decided to just replace it. 
I am not actively developing this plugin, but if I do, I'll look more into this. Also if anyone else knows how to do it, they can feel free to suggest a change and I'll apply it.

**Comment by gytosas** [comment]
No worries. There are already plugin with a lot of customizations for xp drops, but for me it is to much, as I only want to add damage dealt line. 
I will link that plugin, in case u interested and would want to/could find what u need in code.
https://github.com/l2-/template-plugin/tree/78a7c032d22db6650d16d482e570a4b8c88f7900

**Comment by geeckon** [comment]
Same issue as https://github.com/geeckon/instant-damage-calculator/issues/2
